### ISSUE TITLE
Pipeline details page text- Pipeline features text

### ISSUE THREAD

**Issue by leacd** [cdapio/website#23]
Please increase the text of these two features descriptions

**Visual data pipeline designer**
UI to build data pipelines using a point and click designer studio

**Data Discovery and Governance**
UI to build data pipelines using a point and click designer studio

You can add up to 50 characters per each description. (titles are ok)

**Comment by bdmogal** [comment]
Visual data pipeline designer
Build data pipelines by stitching together sources, transformations, sinks and other nodes using a simple, point and click pipeline studio UI 

Data Discovery and Governance
Data discovery based on technical, operational and business metadata; Lineage for root cause and impact analysis.
