### ISSUE TITLE
Reduce font size everywhere.

### ISSUE THREAD

**Issue by bdmogal** [cdapio/website#46]

**Comment by leacd** [comment]
(headers fonts size stay the same)

Opening paragraphs for all pages (Please make sure that the font is regular, not medium or bold)
```
.hero__paragraph {
    font-size: 20px;
    letter-spacing: .3px;
```
-------------------------
TEXT SIZE for
Home - "why CDAP" cards
Pipelines - "Pipelines benefits" 
```
.why__block-body {
    color: #666;
    font-size: 16px;
    line-height: 1.5;
    letter-spacing: .2px;
```
Please make the width of the text 270px instead of 300
------------------
TEXT SIZE for
Home - "CDAP features" 
Pipelines - "Plugins" 
Community - "Stay informed" 
```
:root p:not(.not-apply) {
    color: #333;
    margin: 0;
    font-size: 16px;
```
---------------------
Home - Accelerators cards text size
```
.accelerators__item-body {
    height: 120px;
    overflow: hidden;
    font-size: 14px;
    letter-spacing: .15px;
    line-height: 20px;
    margin: 6px 0 0;
```
--------------------
TEXT SIZE for
Home - Testimonial
```
.testimonials__testimonial {
    font-size: 20px;
    font-weight: 300;
    letter-spacing: .2px;
    color: #333;
    line-height: 30px;
    margin-bottom: 0;
```
----------------------
TEXT SIZE for
Get started page (subtitle text)
```
:root p:not(.not-apply) {
    color: #333;
    margin: 0;
    font-size: 18px;
```
----------------------
TEXT SIZE for
Accelerators - descriptions
```
:root p:not(.not-apply) {
    color: #333;
    margin: 0;
    font-size: 16px;

```
-----------------------
Accelerators details pages (e.g. Analytics) - Features descriptions
```
:root p:not(.not-apply) {
    color: #333;
    margin: 0;
    font-size: 16px;
```
Reduce vertical space between features descriptions
```
@media (min-width: 992px)
.features__block {
    min-height: 90px;
```
--------------------------
